```{r}

library(circular)
library(chron)
library(lubridate)
library(dygraphs)
library(ggplot2)
library(sqldf)
options("scipen"=100, "digits"=4)
```

Cleaning the data

```{r}
data<-read.csv("output.csv", sep=",", header = F)
##removing the unneccessary columns 
data<-data[,-1]
data<-data[,-2]
ddata<-data
head(data)
```

Convrt the column to class time and data


```{r}
class(data$V5)
##converting the time
data$V7<-times(data$V7)
data$V8<-times(data$V8)
##converting the dates 
data$V5<-as.Date(data$V5,format="%d/%m/%Y")
data$V6<-as.Date(data$V6,format="%d/%m/%Y")

```

Adding a new column as the duration of each calls made

```{r}
data$call.duration<-times(data$call.duration)
data$call.duration<-data$V8-data$V7
class(data$call.duration)
head(data)
```

naming the columns approprately 

```{r}
colnames(data)<-c("caller","reciever","start.date","End.data","start.time","end.time","call.type","call.cost","call.duration")
head(data)
```

Which accounts has the biggest impact based on different factors, i have outlined the factors in the my comments

```{r}
#this is the account number who has called the most in the group and the number of time
most.called.number <- sort(table(data$caller),decreasing=TRUE)[1:1]
print(most.called.number)
#these are the 50 most numbers that has started the most calls and the number of times
most.called.numbers <- sort(table(data$caller),decreasing=TRUE)[1:50]
#print of the top 20s from the the top 50s group
most.called.numbers<-data.frame(most.called.numbers)
print(most.called.numbers[1:20,])

#these 50 accounts have made 23162 calls from the total number of 42938
sum(most.called.numbers)
#so its simple math, so only these 50 accounts have made the 53.94% of the calls in the whole data   
23162/42938


#finding the minimum number of users who impacts 90% of users 
most.influences <- sort(table(data$caller),decreasing=TRUE)[1:88]
most.influence<-data.frame(most.influences)
most.influence<-cbind(account = rownames(most.influence), most.influence) 
row.names(most.influence)<-1:nrow(most.influence)

#the 90%of population who has impact
sum(most.influence$most.influences/42938)


#this is the account who has recieved the most call
most.recieved.number <- sort(table(data$reciever),decreasing=TRUE)[1:1]
print(most.recieved.number)
#these are the 20 people who has the most recieved calls by others
most.recieved.numbers <- sort(table(data$reciever),decreasing=TRUE)[1:20]
print(most.recieved.numbers)

#the following variable is called best.friends, these are the most frequent calls among two account numbers
best.friends<-sqldf('SELECT caller, reciever, COUNT(*) AS frequency
      FROM data 
      GROUP BY (caller||reciever) 
      ORDER BY COUNT(*) DESC')

# i am going to print the top 20 of most numbers that has spoken to each others with the frequencies 

best.friends[1:20,]

ddata<-data
```

question two

creating a random list of 25%
```{r}
number.obs<-dim(data)[1]
population<-sample(1:number.obs,.25*number.obs)
population<-data[population,]

```




